### ISSUE TITLE
OPEN CV PROBLEM 

### ISSUE THREAD

**Issue by anonymousm3** [adeept/adeept_picar-b#11]
I tried to run this followring code

pi@raspberrypi:~/adeept_picar-b/server $ sudo python3 webServer.py

But gives me an error response.. 

pi@raspberrypi:~/adeept_picar-b/server $ sudo python3 webServer.py
......................pause..........................
Traceback (most recent call last):
  File "/home/pi/adeept_picar-b/server/webServer.py", line 26, in <module>
    import app
  File "/home/pi/adeept_picar-b/server/app.py", line 8, in <module>
    from camera_opencv import Camera
  File "/home/pi/adeept_picar-b/server/camera_opencv.py", line 2, in <module>
    import cv2
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

**Comment by Egonito** [comment]
I didn´t have this issue so sorry i can´t help.

:3
