### ISSUE TITLE
Error when launching webServer.py

### ISSUE THREAD

**Issue by ghost** [adeept/adeept_picar-b#16]
Please help me to resolve this error :
Traceback (most recent call last):
  File "/home/theprogramerj/robot/server/webServer.py", line 14, in <module>
    import RPIservo
  File "/home/theprogramerj/robot/server/RPIservo.py", line 17, in <module>
    pwm = Adafruit_PCA9685.PCA9685()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Adafruit_PCA9685/PCA9685.py", line 74, in __init__
    self._device = i2c.get_i2c_device(address, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Adafruit_GPIO/I2C.py", line 63, in get_i2c_device
    busnum = get_default_bus()
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/Adafruit_GPIO/I2C.py", line 55, in get_default_bus
    raise RuntimeError('Could not determine default I2C bus for platform.')
RuntimeError: Could not determine default I2C bus for platform.

**Comment by adeept** [comment]
Hello,

Your issue is due to I2C not being turned on. You can use the command 'i2cdetect - y 1' to detect it. If the following prompt appears, it means I2C is not turned on:

 

So we need to turn on I2C. The steps to turn it on are as follows:


Run the command sudo raspi-config
Select '3 Interface Options'
Select "P5 I2C" (I2C interface)
Select 'Yes' to turn on I2C
This should solve the problem of I2C not being turned on.









Best!
------------------------------------------
Adeept Tech Support Team
Adeept Technology Co., Ltd.
E-mail: ***@***.***
Web: www.adeept.com










---- Replied Message ----
From ***@***.***> Date 12/1/2024 20:24 To ***@***.***> Cc ***@***.***> Subject [adeept/adeept_picar-b] Error when launching webServer.py (Issue #16)  
Please help me to resolve this error :
 Traceback (most recent call last):
 File "/home/theprogramerj/robot/server/webServer.py", line 14, in
 import RPIservo
 File "/home/theprogramerj/robot/server/RPIservo.py", line 17, in
 pwm = Adafruit_PCA9685.PCA9685()
 ^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/Adafruit_PCA9685/PCA9685.py", line 74, in init
 self._device = i2c.get_i2c_device(address, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/Adafruit_GPIO/I2C.py", line 63, in get_i2c_device
 busnum = get_default_bus()
 ^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/dist-packages/Adafruit_GPIO/I2C.py", line 55, in get_default_bus
 raise RuntimeError('Could not determine default I2C bus for platform.')
 RuntimeError: Could not determine default I2C bus for platform.

**Comment by ghost** [comment]
Thanks you
